version: '3.9'
services:
  chatbot:
    build: .
    restart: always
    # Specify a .env file for credentials
    # the `AWS_INSTANCE_URL` environment variable will be prepended to that file
    env_file: .env
    ports:
      - "8000:8000"

    volumes:
      - .:/app